### ISSUE TITLE
Support for pulse input

### ISSUE THREAD

**Issue by vegarroe** [gskjold/AmsToMqttBridge#160]
Option for a pulse input with setting for the meters pulses/kwh (typical 500 or 1000 pulses/kwh). This was what I used before the HAN interface was released. It would be nice to support options of photo electric sensor (e.g. BH1750 sensor) from pulse LED on front of the meter or the electric pulse output to GPIO for those that have access to that. BH1750 is a I2C sensor giving lux measurement and I used < 30 as off and >150 as on for the pulse LED with result in almost no loss of pulses.

Value (pulses) to be sent on MQTT as:
- pulses since last sending (send every 2.5s as part of already existing JSON)
- pulses this hour (reset to zero each hour)

Background: Pulse option will give a possibility to get continuous hourly consumption without waiting for the once/hour value from the meter. This is important due to the new differentiated cost for grid connection that is calculated on the one hour per month with the peak kwh/h, typical in steps, 0-2, 2-5, 5-10 etc. Seeing accumulated hour consumption will give possibility to use this to shut off high loads in a smart home solution before the hour is passed and it is too late.

I have some code I can share if this option will be evaluated and eventually implemented but I'm not the best programmer.

**Comment by gskjold** [comment]
I would argue that you can still calculate a continuous kwh reading by adding (active import / 1000) * (millis since last value / 3600000) every time you receive a new active import value. But please feel free to argue why pulse input would be better :)

Also, the incremental electricity tariff you mention is something I am currently implementing some code for, more details on that later.
