### ISSUE TITLE
"Energy use last month" is all 0's

### ISSUE THREAD

**Issue by mikkel75** [gskjold/AmsToMqttBridge#184]
I've been running 2.xx (now 2.0.2) since release and never seen "Energy use last month" been anything but 0's - do I have to set something up to enable this? Other graphs works just fine :)

Don't mind the ESP voltage - it's measuring the voltage of the superCap setting before a DC/DC to the ESP...

**Screenshots**
![image](https://user-images.githubusercontent.com/22839537/147955849-453d0aa6-7b9b-48f7-b96e-83429f2af602.png)

**Hardware information:**
 - Meter: Kamstrup Omnjipower
 - AMS reader: ESP8266

**Relevant firmware information:**
 - Version: 2.0.2
 - MQTT: yes
 - HAN GPIO: UART2 GPIO13

**Comment by hanseinar** [comment]
Same in my installation. Last month is all 0. Online for one week.

**Comment by sfk2611** [comment]
I have exactly same issue. But the strange thing is that I have two readers, one on each of my two Aidon meters.
Both readers installed at same time and running 2.02.
One reader is showing energy used last month. The other one is showing only zeros.

AMS reader: ESP8266
GPIO12
No MQTT

**Comment by sfk2611** [comment]
Pictures to my comment above

![image](https://user-images.githubusercontent.com/97066825/147989698-4e52a75c-2582-4093-aa1f-fe7b9838cb35.png)
![image](https://user-images.githubusercontent.com/97066825/147989867-5d82cf33-10f0-4f38-b7c9-3d0925ccc785.png)

**Comment by gskjold** [comment]
Interesting. Which country and meter? Question goes for all of you.

**Comment by mikkel75** [comment]
Denmark
Kamstrup Omnipower
ESP8266

**Comment by TilSjoes** [comment]
Same here..
![image](https://user-images.githubusercontent.com/47720461/148031796-3fb4e357-396c-43ed-b906-db7cd98240c3.png)
Norway
Aidon 6525
TN 400V

**Comment by sfk2611** [comment]
Norway
Aidon 6525
ESP8266
GPIO12

**Comment by ArnieO** [comment]
A Pow-U (GPIO12) user reports a similar issue. 
Norway, unknown meter type.

Could it be that the algorithm is not robust enough to recover if one midnight reading is lost?

![image](https://user-images.githubusercontent.com/10295178/148048258-ea0f3cf8-193e-47fd-b449-f4c72bdb05ac.png)

**Comment by mikkel75** [comment]
I guess it could be, but in my 'backend' Domoticz I have valid log for many days provided by the ams2mqtt...also the "enegy use last 24h" also have valid data for 00.00

**Comment by servswitch** [comment]
> A Pow-U (GPIO12) user reports a similar issue. Norway, unknown meter type.
> 
> Could it be that the algorithm is not robust enough to recover if one midnight reading is lost?
> 
> ![image](https://user-images.githubusercontent.com/10295178/148048258-ea0f3cf8-193e-47fd-b449-f4c72bdb05ac.png)

Information about my meter:
Kaifa -> model: MA105H2E
RSSI: -81 dBm
Uptime: 4 days

Will move WiFi router closer to AMS reader to get better signal.

I did upgrade the firmware to version 2.0.2 a couple of days ago. I cannot tell if it was on the same day as daily energy usage stopped showing up, but it is close.

**Comment by ArnieO** [comment]
> Will move WiFi router closer to AMS reader to get better signal.

I don't think -80 dBm RSSI is the issue here, ref also the [interesting input from @mikkel75](https://github.com/gskjold/AmsToMqttBridge/issues/184#issuecomment-1004749496).
We'll have to wait for @gskjold to find time to look into this!

Strange issue... My Pow-K with v2.0.2 on a Kamstrup meter has not so far (14 days) failed in this way.

**Comment by madsbg** [comment]
I know it doesn't help you guys with problems, but like @ArnieO my Pow-K with v.2.0.2 in Kamstrup Omnipower / Denmark has also been very stable.
![v2 0 2 15 days runtime](https://user-images.githubusercontent.com/73168571/148068186-c2629981-19fa-4819-99b9-635bb46cb11e.png)

**Comment by ArnieO** [comment]
@madsbg All information could help to pinpoint the problem, so thank you!
Apparently you must have started on v2.0.0, then upgraded from there:
![image](https://user-images.githubusercontent.com/10295178/148073142-c8120b47-78a9-463f-96c1-f274b77e5b48.png)

I also note that your device has been up 15 days, some of us experience irregular reboots on v2.0.x, see https://github.com/gskjold/AmsToMqttBridge/issues/174. Mine has been up 3 days now. 

PS: Impressively low consumption! 😮

**Comment by hanseinar** [comment]
Norway
Aidon 6525
ESP8266 D1 mini Lite
GPIO13
And this TTL to MBUS:  https://www.aliexpress.com/item/32834331647.html

**Comment by ArnieO** [comment]
And now it is my turn.
Symptoms:
- Zero in the month-graph.
- The hourly value also seems to be stuck since 22 yesterday.
- The instantaneous power presentation works as normal.

Setup:
- Current uptime: 4 days
- Kamstrup 3-phase TN / Norway
- Pow-K (ESP8266), UART0
- v2.0.2

@gskjold: Note that the hourly values seems to be shifted 1 hour in dayplot.json:
![image](https://user-images.githubusercontent.com/10295178/148173461-2ed2698d-f3ef-4dd4-a7a7-9388fcc3702c.png)
![image](https://user-images.githubusercontent.com/10295178/148173550-2a97b0f0-e477-43c1-b261-d869cd24b0a9.png)
![image](https://user-images.githubusercontent.com/10295178/148173762-215f239c-60e1-406a-95d0-f0a2f08b0ed7.png)

**Comment by gskjold** [comment]
Very interesting, and thank you for all the input. I think this may be connected to when and how the code does the calculations for month. I have some ideas on where to start looking. Will see if I can get to look at it this weekend.

**Comment by ArnieO** [comment]
Huh, strange. Now the hourly reading started moving again:
![image](https://user-images.githubusercontent.com/10295178/148179670-928e1b74-24a7-467b-b6c0-9c152ff70fd1.png)

I find it very improbable that nine subsequent identical hourly consumptions is correct.

**Comment by gskjold** [comment]
Looks like the last hourly reading it managed to get was at 22:00, then missed all of then until 07:00. It will spread the use over all hours in between. I've made some changes for v2.0.3 that may fix this issue. Attaching build.

[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/7813763/esp8266.zip)
[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/7813765/esp32.zip)

**Comment by ArnieO** [comment]
Understood: If it misses a List 3 reading it will average over the missing period(s) when a new valid List 3 is read. 
But it sounds very strange that it should suddenly miss all List 3 readings for such a long period... 
Thank you for update! I will upgrade later today then we'll just have to wait and see.

**Comment by sfk2611** [comment]
Thank you for a prompt solving action. 
Vennlig hilsenJon Taby

**Comment by mikkel75** [comment]
I get frame errors with debug image:

(D) (readHanPort) Authentication tag:
(D) 61 AD DC BD  47 72 9F 60  97 2D E2 EE
(W) (readHanPort) Frame checksum error
(D) (AmsWebServer)Serving /data.json over http...
(D) (AmsWebServer)Serving /data.json over http...
(D) (readHanPort) Frame dump (491b):
(D) 7E A1 E9 41  03 13 C6 37  E6 E7 00 DB  08 4B 41 4D
(D) 45 01 AE 90  F6 82 01 D0  30 00 14 30  C2 0F 00 00
(D) 00 00 0C 07  E6 01 05 03  0B 29 14 FF  80 00 00 02
(D) 41 0A 0E 4B  61 6D 73 74  72 75 70 5F  56 30 30 30
(D) 31 09 06 01  01 01 08 00  FF 06 00 23  16 99 09 06
(D) 01 01 02 08  00 FF 06 00  00 00 00 09  06 01 01 03
(D) 08 00 FF 06  00 00 4C 55  09 06 01 01  04 08 00 FF
(D) 06 00 05 2D  51 09 06 01  01 00 00 01  FF 06 01 44
(D) 7F 24 09 06  01 01 01 07  00 FF 06 00  00 01 83 09
(D) 06 01 01 02  07 00 FF 06  00 00 00 00  09 06 01 01
(D) 03 07 00 FF  06 00 00 00  00 09 06 01  01 04 07 00
(D) FF 06 00 00  00 2A 09 06  00 01 01 00  00 FF 09 0C
(D) 07 E6 01 05  03 0B 29 14  FF 80 00 00  09 06 01 01
(D) 20 07 00 FF  12 00 DF 09  06 01 01 34  07 00 FF 12
(D) 00 E4 09 06  01 01 48 07  00 FF 12 00  E3 09 06 01
(D) 01 1F 07 00  FF 06 00 00  00 6C 09 06  01 01 33 07
(D) 00 FF 06 00  00 00 51 09  06 01 01 47  07 00 FF 06
(D) 00 00 00 20  09 06 01 01  15 07 00 FF  06 00 00 00
(D) D1 09 06 01  01 29 07 00  FF 06 00 00  00 A0 09 06
(D) 01 01 3D 07  00 FF 06 00  00 00 12 09  06 01 01 21
(D) 07 00 FF 12  00 63 09 06  01 01 35 07  00 FF 12 00
(D) 63 09 06 01  01 49 07 00  FF 12 00 1B  09 06 01 01
(D) 0D 07 00 FF  12 00 63 09  06 01 01 16  07 00 FF 06
(D) 00 00 00 00  09 06 01 01  2A 07 00 FF  06 00 00 00
(D) 00 09 06 01  01 3E 07 00  FF 06 00 00  00 00 09 06
(D) 01 01 16 08  00 FF 06 00  00 00 00 09  06 01 01 2A
(D) 08 00 FF 06  00 00 00 00  09 06 01 01  3E 08 00 FF
(D) 06 00 00 00  00 09 06 01  01 15 08 00  FF 06 00 0E
(D) 48 04 09 06  01 01 29 08  00 FF 06 00  0C 75 F9 09
(D) 06 01 01 3D  08 00 FF 06  00 08 58 9B  F1 EF 9D 53
(D) 55 01 5C 46  CE 38 13 52  8C 17 7E
(D) (readHanPort) System title:
(D) 4B 41 4D 45  01 AE 90 F6
(D) (readHanPort) Initialization vector:
(D) 4B 41 4D 45  01 AE 90 F6  00 14 30 C2
(D) (readHanPort) Additional authenticated data:
(D) 30 DF 15 04  2E DB 4A E4  AB A1 C6 5E  4F 69 2E B9
(D) 60
(D) (readHanPort) Authentication tag:
(D) F1 EF 9D 53  55 01 5C 46  CE 38 13 52
(W) (readHanPort) Frame checksum error
(D) (loop) Used 1 ms to update temperature
(D) (AmsWebServer)Serving /data.json over http...

AND YES - I have checked keys :)

**Comment by gskjold** [comment]
You get checksum error on all frames? No change in the code up to this point where it throws checksum error, so there is no reason why that should be different from 2.0.2. Have you tried to re-seat the module? (take out and put back in)

**Comment by mikkel75** [comment]
Hmm switching back to 2.0.2 (which I used before trying debug build) and it went to factury defaults - forgot all settings even wifi :(
Now - after setting correct keys - I get

(W) (readHanPort) Invalid HDLC, returned with -9

How do I specify it's a Kamstrup reader - it detected that right before?

**Comment by gskjold** [comment]
Yes, reverting will clear config.
2400 baud 8N1 ?
You cannot specify meter type, it will be detected.

**Comment by mikkel75** [comment]
Ah yes you are right 2.0.2 works after setting back to 8N1 - but debug image still fails with checksum error on every frame.
Have also tried software serial, same result.

**Comment by mikkel75** [comment]
I have tried debug image again while double checking settings - I still get checksum errors....2.0.2 works as before...

**Comment by gskjold** [comment]
ok, will look at it next time I have room to set up test with encrypted payloads

**Comment by gskjold** [comment]
Hang on, I see it now :) New image attached

[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/7814600/esp32.zip)
[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/7814601/esp8266.zip)

**Comment by mikkel75** [comment]
Much better - now I have valid data...Will report back wrt "Energy use..."

**Comment by ArnieO** [comment]
Yesterday I saw this:
![image](https://user-images.githubusercontent.com/10295178/148339491-a08402d6-f9ea-4870-aaae-24a3e2b5dad9.png)

Now, with 220105.2, this:
![image](https://user-images.githubusercontent.com/10295178/148339570-ce7f1416-dcb3-486a-95d4-f058b934474d.png)

28 is clearly wrong, and yesterday shows zero.

**Comment by gskjold** [comment]
Agree, but given the nature of the algorithm I say we give it one more midnight to see if it stabilize.

**Comment by mikkel75** [comment]
Data from latest beta image:
Still 0's unfortunately...

![image](https://user-images.githubusercontent.com/22839537/148343561-90b7da84-ef3f-4546-a03f-eeb04c5d57f4.png)

**Comment by gskjold** [comment]
I've managed to reproduce this at home now, should be easier to debug.

**Comment by gskjold** [comment]
I found a few problems in that code actually. Attached is a new firmware to fix it. May not produce any (or maybe incorrect) value on first midnight. There is permanent logging in the month plot code, so check serial or telnet at midnight. Debug level is ignored, so it will output on any level. Will probably generate message "Invalid future timestamp, resetting" and not produce any value over first midnight.

If you are like me and do not want to be up at midnight, but have a linux box at hand, add this to crontab:
59 23 * * * telnet 192.168.0.0 >> amslog.txt 2>&1
Remember to replace IP.

[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/7823649/esp32.zip)
[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/7823651/esp8266.zip)

**Comment by mikkel75** [comment]
I didn't update to latest beta but running 220105.02 - BUT I have my first bar ever in the month status :)

![image](https://user-images.githubusercontent.com/22839537/148505735-7ec10227-9860-438f-a8d3-d6aaebb35f45.png)

**Comment by servswitch** [comment]
I upgraded to 220106.1 last night and lost the few bars I had and did not get one during this first night.
![image](https://user-images.githubusercontent.com/92640627/148518150-736aa234-1242-4629-b695-691a2f7d35a4.png)

**Comment by ArnieO** [comment]
Upgraded to 220106.1 this morning, and unfortunately; no.
Zero on the hourly graph since this morning.
Would wipe and reflash help?

**Comment by gskjold** [comment]
Seriously? Have no real recommendations for you unfortunately. I'm starting to regret this feature...

**Comment by ArnieO** [comment]
It changed after next hour passing, showed averaging (10 identical hour values) over previous 10 hours.

Strange all this, I really understand the frustration!

**Comment by TilSjoes** [comment]
> Seriously? Have no real recommendations for you unfortunately. I'm starting to regret this feature...

Please don't :) Your efforts are highly appreciated!!
Frode

**Comment by ArnieO** [comment]
@gskjold: All the feedback in this thread is a strong indication that this is a strong and highly appreciated feature. So please don’t let the current minor bumps discourage you!

**Comment by gskjold** [comment]
Thanks, appreciate the support. This has stolen way more time from me than any of the other features, so I really hope I'm able to make it stable at some point.

Got the first bar back on the graph now on my test setup, I hope all of you guys have the same positive result.

**Comment by ArnieO** [comment]
Too early here for any bar on the bottom graph, as I installed 220106.1 yesterday morning.
The rest is just fine! 👍

**Comment by servswitch** [comment]
I got two days/bars at the same time after two nights on 220106.1. The value listed is not correct, so I will give it a third night to see if it starts showing correct values. 
![image](https://user-images.githubusercontent.com/92640627/148638881-5c2cb54e-2916-4094-8d09-09350b19177b.png)

**Comment by gskjold** [comment]
To be expected, It split the value over two days. It should give a correct result on next calculation

**Comment by hanseinar** [comment]
Sorry to say, but no bars at my installation. There have never been bars in the month graph.
<img width="560" alt="1" src="https://user-images.githubusercontent.com/8856635/148639500-677e4f3b-aa2a-4dc1-b017-3eac9d23232e.png">

**Comment by gskjold** [comment]
Just checking, have you passed at least two midnights with that build version? In any case, crossing fingers it will give you something tomorrow

**Comment by hanseinar** [comment]
Yes, midnight passed two times.

**Comment by sfk2611** [comment]
I am back on 2.02 on both of my readers. The first trial version did not help.

I thrust on you and install the last trial version when confirmed to work.

 

As mentioned before. Version 2.02 did correct on one of the readers in both diagrams, but the other did not sum in the month diagram. Same meter for both and GPIO12.

**Comment by hanseinar** [comment]
Good morning. 
Progress! For the first time there is bars on the month graph. Strange results, bur results. Perhaps they "calibrate" in the future,
![2](https://user-images.githubusercontent.com/8856635/148677411-ae026d88-bfd0-40f2-aefc-4b52f7a5aed1.png)

**Comment by hanseinar** [comment]
Not sure if it's the right time or the right topic, but I give it a try.

Nordpool has a free API to retrieve hourly rates for the next day. Node-RED has even a node "nordpool-api-plus" which retrieves these values. You choose in the node from drop down power areas from all over Scandinavia. I am more curios for the daily and monthly cost than the consumption.
Since this feature is a bit bumpy, might it be an idea to look at it from a cost perspective rather than a consumption perspective even if they are related? Maybe we already at the limit of what esp8266/32 can handle? Perhaps instead of bars, just cost today, and cost month? Just thoughts.

**Comment by gskjold** [comment]
This statement that Nordpool has a free API has come up before. Last time I checked this is not true, and the plugins out there (for node-red and alike) uses the same endpoint that nordpoolgroup.com website uses, where it is clearly states:

"Nord Pool does not permit automatic extraction of data or other usage that reduces the performance of the website. Any such extraction or usage will lead to the user being blocked from the website without further notice"
https://www.nordpoolgroup.com/About-us/Terms-and-conditions-for-use/

If this turns out not to be true, please refer me to the correct API endpoints together with terms and conditions.

However, I have implemented support for ENTSO-E API, but this is only possible with ESP32 since there is not enough available RAM with the ESP8266 to perform a HTTPS request.

![screenshot](https://user-images.githubusercontent.com/4446828/148678954-f75bc653-9aee-442f-b07a-956708f4193b.png)

**Comment by hanseinar** [comment]
Ok, not aware of that. I reed the statement slightly different.  "extraction of data or other usage that _reduces the performance_ of the website". Perhaps one extraction pr. day not reduse the performance of the website, and the statement say nothing about private use, but that discussion is OT. I've asked them in a mail. Awaiting answer.

**Comment by gskjold** [comment]
In my experience you should read a legal statement like this:
Nord Pool does not permit:
1. Automatic extraction of data 
or 
2. Other usage that reduces the performance of the website

In any case I refuse to implement any API which does not have public terms and conditions that states that it is free to use. 
Also, the api endpoints at nordpoolgroup.com are clearly tailored to the views at their website, which suggests that they will change the implementation without notice when they change the design of their site.

**Comment by ArnieO** [comment]
I have already had dialogues with both NordPool and ENTSO-E, and confirm what @gskjold says. 

The big difference is:
- ENTSO-E is a EU site, its main mission is to inform the public.
- NordPool is an enterprise, its main mission is to generate revenue.

**Comment by bardahlm** [comment]
Regarding cost calculation: This could be calculated client side instead of server side, ie by javascript that fetches the needed prices from whatever sources are available for the user. There are quite a lot of parameters that make up the price of electricity so calculating real price is complex. Capacity on the ESP should be used to deliver a steady stream of metrics to other systems that can make use of those metrics to make decisions on what to do.

**Comment by TilSjoes** [comment]
Just a quick feedback. I don't know if it is relevant anymore, but for me the monthly summary seems to be working and adjusting :)
Thanks for all the help!
![image](https://user-images.githubusercontent.com/47720461/149113866-74643bdc-80fa-4d1b-854e-bf16316b4069.png)
The last readings pr. day are also correct!
Frode

**Comment by tronde-ams** [comment]
Mine is OK for energy, but has skipped energy prices for some reason. Unfortunately no active logging at the moment, but it was OK last midnight. No prices as MQTT or json either. I have two modules running 2.0.2 which shows prices.

<img width="507" alt="2022-01-12_182107" src="https://user-images.githubusercontent.com/97398751/149190169-b73e10ca-b9ef-4f44-8d6d-aea2fb0b9077.png">

**Comment by tronde-ams** [comment]
At the momet it gives some older prices as MQTT, but "null" as json.
![price](https://user-images.githubusercontent.com/97398751/149208326-c107ef0a-128a-4f8d-958f-2d7e7daf23fc.jpg)

Logging data appears to be corrupt. I have not changed or re-started anything except the logging since yesterday where logging appeared OK.

Current log

<ESC>[0m(D) (AmsWebServer)Serving /data.json over http...
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(D) (loop)(C1) Used 0 ms to update temperature
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(D) (AmsWebServer)Serving /data.json over http...
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(D) (AmsWebServer)Serving /data.json over http...
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(D) (AmsWebServer)Serving /data.json over http...
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(D) (loop)(C1) Used 0 ms to update temperature
<ESC>[0m(D) (AmsWebServer)Serving /data.json over http...
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(D) (AmsWebServer)Serving /data.json over http...
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(D) (AmsWebServer)Serving /data.json over http...
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(I) (readHanPort)(C1) Valid data, start at byte 18
<ESC>[0m(D) (loop)(C1) Used 0 ms to update temperature
<ESC>[0m(D) (AmsWebServer)Serving /data.json over http...

**Comment by tronde-ams** [comment]
New day, and energy prices came back. Also correct on json and MQTT.
Energy use is still correct.
No changes to log.


![2022-01-13_000042](https://user-images.githubusercontent.com/97398751/149237135-ab5c6068-749a-45ee-8a69-bbd00b5a2195.jpg)

**Comment by gskjold** [comment]
Added #198 for energy price problem.

As for logging, I have added a extra level "Verbose" if you want to see the frame dump.


Good to hear from you all that the graph stabilized! Thank you so much for all your feedback on this issue.

Considering this issue as resolved.

**Comment by ArnieO** [comment]
🥇
