### ISSUE TITLE
Summer-time corrupted the data. What to do?

### ISSUE THREAD

**Issue by fyzlk** [gskjold/AmsToMqttBridge#255]
I just use pow-U out of the box, following instructions, without digging deep into it.
And it worked quite well for more than one month, except of small troubles with 
periods of bad response. But over all, very useful in this time of various crises.

Until Sunday morning, March 27th 2022,  the first day of summer time. The consumption 
of the last day became zero, and some hour-consumptions at "the edges" of the shown 
interval became zero. Now 2 days later the latter shows O.K., but now all the history data 
back to March 21st became zero.

So how to reset the thing? Will the Factory reset really wipe all data? 
Will it then start working properly - is it really wiping out all the bad data?

Or what is this "Debugging" Feature? What can I ask the program to do?
Reboot does not help, Reset button does not help.

**Comment by henriklund** [comment]
There are some bugs in the firmware (even in v2.0.11) that can cause historical data to be / become incorrect. This is as far as I know still 'work in progress' and there are fixes planned for the coming [v2.1.0](https://github.com/gskjold/AmsToMqttBridge/milestone/22?closed=1).

What I would suggest you to do is to include following info so that troubleshooting could be more efficient (part of a normal request for support):

**Hardware information:**
 - Meter: [e.g. Aidon]
 - AMS reader: [e.g. Pow-U, ESP32 etc]
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: [e.g. 1.5.0]
 - MQTT: [yes/no]
 - HAN GPIO: [e.g. GPIO5]
 - Temperature sensors [e.g. 3xDS18B20]planned
