### ISSUE TITLE
Sharing consumption value of x highest usage hours.

### ISSUE THREAD

**Issue by kardesken** [gskjold/AmsToMqttBridge#302]
Firstly, I'm really impressed with this software. 
And with the new pricing system in Norway with monthly threshold, I was happy to see that this was implemented in AmsToMqttBridge.

I'm trying to implement an "alarm" going off when I'm close to go above a threshold. (So perhaps I can pause the laundry until the the new hour starts).
To do this I need to know the consumption in kWh for (again in Norway) the 3 highest hours.

Now I'm storing all hours in my smarthome system, and calculate the average consumption. But its not a perfect system. With to many hours getting missed. And your sw seems to be doing a much better job of this than my automation.

My automation is something like this.
Data:
  Highest hr: 12kWh
  Second highest hr: 10kWh
  Third highest hr: 7,8kWh
Average is now 9,9kWh. 

If I now use more than 8kWh for an hour, I will go up one threshold. So my "alarm" will now notify me when my consumption for the hour is at 7,2kWh (or 90% of maximum capacity for one hour without going over a threshold).

In your sw there is a setting in the "Tariff thresholds" to set the "average of top hours".
Are the top hours stored? And can they be shared to the user?

So if I set the average of 3 hours, the consumption of these three hours could be shared like this perhaps:
Example of data to share:
http://<ams_hostname>/data.json
  "ea" : {             # Energy accounting
    "x" : 0.0,       # Max average of configured amount of hours
     "x1" : 0.0      # Highest consumption hour *New*
     "x2" : 0.0      # Second highest consumption hour *New*
     "x3" : 0.0      # Third highest consumption hour *New*
     "t" : 0,         # Current active month threshold
        "h" : {          # Real time calculation this hour
            "u" : 0.00,  # Consumption
            "c" : 0.00   # Cost

Anyway, thanks for a great program.

**Comment by ArnieO** [comment]
Thank you, this is interesting feedback!
This functionality was relatively recently added to the firmware, and users' ideas and proposals to improve it will certainly be taken into account.

**A short clarification for non-Norwegian users what this functionality is:**
A power tariff was introduced in Norway this summer, to sort of incentivize customers to distribute their load on the grid as much as possible. Examples: If every household charges their EV car at the same time, it means the grid must be dimensioned for that peak load.

How it works: 
If the **_average consumption of your three highest-consuming hours in a given calendar month_** surpasses a threshold, your grid usage bill next month will increase. There are multiple threshold levels, and the levels are increasingly expensive to surpass. And to complicate further, it is up to each grid company to set the threshold levels and associated penalties.

As an example, [my grid company](https://mellom.no/nettleie/nettleiepriser-2022/) has thresholds at 2, 5, 10, 15, 20, 25, and 50kW, and here are the associated costs (in NOK/month):
![image](https://user-images.githubusercontent.com/10295178/185791381-53b77faa-5289-4b66-9107-b821b86e2848.png)

A functionality has been added to the firmware to help follow-up of this - and potentially help the consumer to see when there is a risk of surpassing a threshold so that she/he can temporarily switch off consumers like heated bathroom floors,  electrical water heater, car charging etc... 

Under Configuration/Meter you find this in the bottom left corner a link "Configure tariff thresholds" that opens a submenu.

And here are my settings, based on the above table:
![image](https://user-images.githubusercontent.com/10295178/185791503-6b5eb501-b5a8-4b1d-92bc-0e12cc412ae3.png)

Now, looking back at the main page, the rightmost part of the "Real time consumption" section, I can see: 
![image](https://user-images.githubusercontent.com/10295178/185791565-04cb8b26-de55-400d-8ea1-902ab56012b2.png)

- 4.7 means my average of the top 3 hours this month is 4.7 kWh.
- /5 means that the next threshold I risk surpassing is the 5 kWh limit. So I better watch out... 
 
If I surpass 5 kWh average, this part of next month's grid bill will increase from 279 to 419 NOK.
